# WORK IN PROGRESS
version: '3.8'
services:
    ollama-tg:
        build: .
        container_name: ollama-tg
        restart: on-failure
        env_file:
            - ./.env

        # Uncomment to enable NVIDIA GPU
        # Otherwise runs on CPU only:

        # deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           count: all
        #           capabilities: [gpu]
